### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by MonteCrisply** [FRC-Team-6026/Crescendo#3]
We have a lot of clutter in our code. I'd like to determine what we need to keep, and what we can do away with.
I'd also like to make sure everything is well organized.
 - Go through Constants and clear out values that we don't use, and won't ever use (such as unused PID/SVA values)
 - Go through subsystems and check for hardcoded values that ought to be placed in Constants.

**Comment by ED-EXCORT** [comment]
Changes where made and code was clean up there may be some room for cleanup
